### ISSUE TITLE
Panic when delete and inserting words 

### ISSUE THREAD

**Issue by jayyao97** [vcaesar/cedar#4]
- Cedar version (or commit ref): v0.20.1
- Go version: v1.18

- Operating system and bit: Darwin Kernel Version 22.4.0, arm64
- Can you reproduce the bug at [Examples](https://github.com/vcaesar/cedar/tree/master/examples):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code: 
```Go
package main

import "github.com/vcaesar/cedar"

func main() {
	input := []string{......}
	ce := cedar.New()
	i := 0
	for _, w := range input {
		wByte := []byte(w)
		ce.Delete(wByte)
		ce.Insert(wByte, i)
		i++
	}
}
```
- Log gist:
```
panic: runtime error: index out of range [-126]

goroutine 1 [running]:
github.com/vcaesar/cedar.(*Cedar).consult(...)
        /Users/user/go/pkg/mod/github.com/vcaesar/cedar@v0.20.1/cedar.go:283
github.com/vcaesar/cedar.(*Cedar).resolve(0x1400006e000?, 0x8000000000000000?, 0x461?, 0x9c?)
        /Users/user/go/pkg/mod/github.com/vcaesar/cedar@v0.20.1/cedar.go:424 +0x6c8
github.com/vcaesar/cedar.(*Cedar).follow(0x1400006e000?, 0x461?, 0x9c?)
        /Users/user/go/pkg/mod/github.com/vcaesar/cedar@v0.20.1/cedar.go:134 +0xf4
github.com/vcaesar/cedar.(*Cedar).getNode(0x1400006e000, {0x1400006b720, 0x8, 0x8?}, 0x100000000000020?, 0x1400006b720?)
        /Users/user/go/pkg/mod/github.com/vcaesar/cedar@v0.20.1/fn.go:46 +0x38
github.com/vcaesar/cedar.(*Cedar).get(...)
        /Users/user/go/pkg/mod/github.com/vcaesar/cedar@v0.20.1/fn.go:31
github.com/vcaesar/cedar.(*Cedar).Insert(0x1400006e000, {0x1400006b720?, 0x0?, 0x0?}, 0x80)
        /Users/user/go/pkg/mod/github.com/vcaesar/cedar@v0.20.1/fn.go:118 +0x44
main.main()

Process finished with the exit code 2
```
## Description
I don't know whether my usage is correct or not 
...

**Comment by jayyao97** [comment]
I found that if we split delete and insert actions it won't panic:
```Go
for _, w := range input {
    wByte := []byte(w)
    ce.Delete(wByte)
}
for _, w := range input {
    wByte := []byte(w)
    ce.Insert(wByte, i)
    i++
}
